name: Setup Flutter from repository
description: "Setup Flutter from repository"
inputs:
  ref:
    description: "example: Branch"
    required: false
    default: "stable"
  working_directory:
    description: "working-directory. example: packages/flutter_app"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}
        cache: true
        cache-key: flutter # optional, change this to force refresh cache
        cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

    - name: Cache Pub
      uses: actions/cache@v2
      id: pub-cache
      with:
        path: |
          ${{ env.FLUTTER_HOME }}/.pub-cache
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}

    - name: Get dependencies
      if: steps.pub-cache.outputs.cache-hit != 'true'
      run: flutter pub get
      working-directory: ${{ inputs.working_directory }}
      shell: bash
