name: Setup Flutter from repository
description: "dependencies install step"
inputs:
  ref:
    description: "example: Branch"
    required: false
    default: "stable"
  working_directory:
    description: "working-directory. example: packages/flutter_app"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Install Flutter
      run: ./.github/workflows/scripts/install-flutter.sh ${{ inputs.ref }}
      shell: bash

    - name: Get dependencies
      run: flutter pub get
      working-directory: ${{ inputs.working_directory }}
      shell: bash
