name: Setup Flutter from repository
description: "Setup Flutter from repository"
inputs:
  ref:
    description: "example: Branch"
    required: false
    default: "stable"
  working_directory:
    description: "working-directory. example: packages/flutter_app"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Cache Flutter
      uses: actions/cache@v2
      id: flutter-cache
      with:
        path: _flutter
        key: ${{ runner.os }}-${{ inputs.ref }}-${{ inputs.working_directory }}

    - name: Install Flutter
      if: steps.flutter-cache.outputs.cache-hit != 'true'
      run: git clone https://github.com/flutter/flutter.git --depth 1 -b ${{ inputs.ref }} "$GITHUB_WORKSPACE /_flutter"
      shell: bash

    - name: Add PATH
      run: echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH
      shell: bash

    - name: Cache Pub
      uses: actions/cache@v2
      id: pub-cache
      with:
        path: |
          ${{ env.FLUTTER_HOME }}/.pub-cache
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}

    - name: Get dependencies
      if: steps.pub-cache.outputs.cache-hit != 'true'
      run: flutter pub get
      working-directory: ${{ inputs.working_directory }}
      shell: bash
