name: Setup Flutter
description: "Setup Flutter"
outputs:
  flutter-path:
    description: "Flutter SDK path"
    value: ${{ steps.install-flutter.outputs.CACHE-PATH }}
runs:
  using: "composite"
  steps:
    - name: Parse Flutter version
      id: fvm-config
      uses: kuhnroyal/flutter-fvm-config-action@v1

    - name: Install Flutter
      id: install-flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config.outputs.FLUTTER_CHANNEL }}
        cache: true
