name: Setup Flutter from repository
description: "dependencies install step"
inputs:
  ref:
    description: "example: Branch"
    required: false
    default: "stable"

runs:
  using: "composite"
  steps:
    - name: Install Flutter
      run: ./.github/workflows/scripts/install-flutter.sh ${{ inputs.ref }}
      shell: bash

    - name: Get dependencies
      run: flutter pub get
      shell: bash
