# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_app"
    schedule:
      interval: "weekly"
    groups:
      riverpod-dependencies:
        patterns:
          - "*riverpod*"
          - "build_runner"
      freezed-dependencies:
        patterns:
          - "build_runner"
          - "freezed*"
          - "json_annotation"
          - "json_serializable"
      slang-dependencies:
        patterns:
          - "build_runner"
          - "slang*"
      go-router-dependencies:
        patterns:
          - "build_runner"
          - "go_router*"
      dependencies-patch:
        patterns:
          - "*"
        update-types:
        - "patch"

  - package-ecosystem: "pub"
    directory: "/packages/themes"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/packages/util"
    schedule:
      interval: "monthly"
    groups:
      dependencies-patch:
        patterns:
          - "*"
        update-types:
        - "patch"
