# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/amazon_paapi"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/packages/convenient_widgets"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/rest_api_client"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/packages/themes"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/util"
    schedule:
      interval: "monthly"
