version: "0.2"
language: en
ignorePaths:
  - "**/.pub-cache"
  - "**/android"
  - "**/build"
  - "**/fvm"
  - "**/ios"
  - "**/linux"
  - "**/macos"
  - "**/Pods"
  - "**/test"
  - "**/web"
  - "**/windows"
  - "*.g.dart"
  - "*.gen.dart"
  - "*.lock"
  - "*.xcconfig"
  - .cspell.yaml
  - .git/objects
  - .gitignore
  - .vscode
  - .vscode-insiders
  - dart_defines
  - firebase_options*.dart
  - google-services.json
  - node_modules
  - package-lock.json
  - Package.resolved
  - Podfile
  - project.pbxproj
  - vscode-extension
words:
  - 3537BAHE48
  - Aimiee
  - altfire
  - altive
  - altool
  - appbar
  - appbundle
  - APPL
  - autofetch
  - autofocus
  - Bitcode
  - bluefireteam
  - btype
  - charas
  - checkin
  - checkins
  - Checkmark
  - COCOAPODS
  - codecov
  - codegen
  - codeowners
  - codesign
  - concat
  - Configurator
  - cupertino
  - dorny
  - dotenv
  - draggable
  - endtemplate
  - everyones
  - fastlane
  - firestore
  - flutterfire
  - fullscreen
  - fvmrc
  - gacha
  - gachas
  - gcode
  - gcov
  - gfuid
  - gokou
  - helveticaNeue
  - horiz
  - iframe
  - informations
  - jpcoaltivefat
  - kanban
  - keychain
  - kihon
  - kuhnroyal
  - lcount
  - lcov
  - leoafarias
  - lerp
  - levelup
  - linkify
  - ltrb
  - LTWH
  - miyagawa
  - mocktail
  - MPLUS
  - muramatsu
  - mypage
  - naipaka
  - nonobvious
  - notoSansjp
  - nullsafety
  - pascalcase
  - pbcopy
  - podhelper
  - postbootstrap
  - postclean
  - prefs
  - psql
  - pubspec
  - reauthentication
  - recase
  - refreshable
  - remoteconfig
  - Reorderable
  - revenuecat
  - rgba
  - riscait
  - riverpod
  - Routemaster
  - ryunosuke
  - Schyler
  - setprop
  - SRCROOT
  - ssid
  - subloc
  - temurin
  - todos
  - toggleable
  - unawaited
  - unfocus
  - utsname
  - vsync
  - wholename
  - widgetbook
  - wireframe
  - xcarchive
  - xcconfig
  - xcodebuild
  - xcodeproj
  - xcrun
  - xcworkspace
flagWords: []
