# See: https://docs.codecov.com/docs/codecov-yaml
# validate: curl -X POST --data-binary @codecov.yml https://codecov.io/validate
codecov:
  notify:
    require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...80"

  status:
    project:
      default:
        target: auto
        threshold: 0%
        only_pulls: true
    patch: # for pull requests
      default:
        target: 80%
        threshold: 0%
        only_pulls: true
        paths:
          - "packages/**/lib/"

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

# excluding generated files and examples from the coverage report
ignore:
  - "**/gen/**"
  - "**/stub/**"
  - "**/*.g.dart"

comment: # See: https://docs.codecov.io/docs/pull-request-comments
  layout: "header, diff, files, flags, components, footer"
  behavior: default
  require_changes: true

component_management:
  default_rules:
    paths:
      - "packages/*/lib/**"
      - "!**/stub/**"
      - "!**/gen/**"
      - "!**/*.g.dart"
  individual_components:
    - component_id: flutter_app
      paths:
        - "packages/flutter_app/lib"
