name: flutter_app_template

packages:
  - packages/**

scripts:
  fvm:
    run: melos exec -c 1 -- "fvm install"
    description: fvm install を実行する

  get:all:
    run: melos run get --no-select
    description: pubspec.yamlに従って依存パッケージ・プラグインを取得する

  get:
    run: melos exec -- "fvm flutter pub get"
    description: pubspec.yamlに従って依存パッケージ・プラグインを取得する
    select-package:
      dir-exists: lib

  analyze:
    run: |
      melos exec -- \
        fvm flutter analyze lib/ --fatal-infos
    description: コード解析を実行する

  format:
    run: |
      melos exec -- \
        fvm flutter format --dry-run --set-exit-if-changed lib/
    description: コードフォーマットを整形する

  gen:all:
    run: |
      melos exec -c 1 --depends-on="build_runner" -- \
        fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: 全てのパッケージでコード生成を実行する

  gen:
    run: |
      melos exec -c 1 -- \
        fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: コード生成したいパッケージを選択して実行する
    select-package:
      dir-exists: lib
      depends-on: "build_runner"

  test:
    run: |
      melos exec --dir-exists="test" --fail-fast -- \
        fvm flutter test --coverage
    description: flutter test を実行する

  upgrade:
    run: |
      melos exec -- \
        fvm flutter pub upgrade --major-versions
    description: 依存パッケージメジャーバージョンを更新する
