name: flutter_app_template
repository: https://github.com/altive/flutter_app_template
sdkPath: .fvm/flutter_sdk

packages:
  - "packages/*"

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: true
  version:
    branch: main

scripts:
  postclean: |
    melos exec --flutter -- "flutter clean"
    melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
    melos exec --flutter --file-exists="macos/Podfile.lock" -- "cd macos && rm Podfile.lock"

  postbootstrap: >
    melos exec --flutter --dir-exists=lib/l10n -- "flutter gen-l10n"

  upgrade:
    run: |
      melos exec -- \
        "flutter pub upgrade --major-versions && flutter pub upgrade"
    description: Run upgrade the major version of the pub.
    select-package:
      flutter: true
      dir-exists: lib

  analyze:
    run: |
      melos exec -- \
        flutter analyze . --fatal-infos
    description: Run analyze.
    select-package:
      flutter: true
      dir-exists: lib

  format:
    run: |
      melos exec -- \
        flutter format --dry-run --set-exit-if-changed lib/
    description: Run format.
    select-package:
      flutter: true
      dir-exists: lib

  fix:
    run: |
      melos exec -- \
        dart fix --apply lib
    description: Run dart fix.
    select-package:
      dir-exists: lib

  gen:
    run: |
      melos exec -c 1 -- \
        flutter pub run build_runner build --delete-conflicting-outputs
    description: Run generate code.
    select-package:
      dir-exists: lib
      depends-on: "build_runner"

  gen:watch:
    run: |
      melos exec -c 1 -- \
        flutter pub run build_runner watch --delete-conflicting-outputs
    description: Watch and run generate code.
    select-package:
      dir-exists: lib
      depends-on: "build_runner"

  test:
    run: |
      melos exec --fail-fast -- \
        flutter test --coverage
    description: Run flutter test.
    select-package:
      flutter: true
      dir-exists: test

  pod:all:
    run: |
      melos run pod:ios --no-select
      melos run pod:macos --no-select
    description: Run all pod install.

  pod:ios:
    run: |
      melos exec -- \
        "cd ios && pod install"
    description: Run pod install on iOS.
    select-package:
      dir-exists: [lib, ios]
      file-exists: "ios/Podfile"

  pod:macos:
    run: |
      melos exec -- \
        "cd macos && pod install"
    description: Run pod install on macOS.
    select-package:
      dir-exists: [lib, macos]
      file-exists: "macos/Podfile"

  build:android:prod:
    run: |
      melos exec -c 1 -- \
        flutter build appbundle --dart-define-from-file=dart_defines/prod.json
    description: Build the AppBundle for the production app.
    select-package:
      flutter: true
      dir-exists: [lib, android]

  upload:ios:prod:
    run: |
      melos exec -c 1 -- \
        flutter build ipa --dart-define-from-file=dart_defines/prod.json --export-options-plist="ios/prod/ExportOptions.plist"
    description: Upload the IPA for the production app.
    select-package:
      flutter: true
      dir-exists: [lib, ios]

  # for ReStock app
  deploy:restock:prod:
    run: |
      melos run build:android:prod:restock
      melos run upload:ios:prod:restock
