// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_app/test/pages/riverpod_example_page/async_notifier_provider_page/async_notifier_provider_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_app/pages/riverpod_example_page/util/fake_dio.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FakeDio].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeDio extends _i1.Mock implements _i2.FakeDio {
  @override
  _i3.Future<_i2.Response<List<Map<String, Object?>>>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i3.Future<_i2.Response<List<Map<String, Object?>>>>.value(
            _FakeResponse_0<List<Map<String, Object?>>>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.Response<List<Map<String, Object?>>>>.value(
                _FakeResponse_0<List<Map<String, Object?>>>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response<List<Map<String, Object?>>>>);

  @override
  _i3.Future<_i2.Response<Map<String, Object?>>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i3.Future<_i2.Response<Map<String, Object?>>>.value(
            _FakeResponse_0<Map<String, Object?>>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.Response<Map<String, Object?>>>.value(
                _FakeResponse_0<Map<String, Object?>>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response<Map<String, Object?>>>);

  @override
  _i3.Future<_i2.Response<List<Map<String, Object?>>>> delete<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #queryParameters: queryParameters,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i3.Future<_i2.Response<List<Map<String, Object?>>>>.value(
            _FakeResponse_0<List<Map<String, Object?>>>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.Response<List<Map<String, Object?>>>>.value(
                _FakeResponse_0<List<Map<String, Object?>>>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response<List<Map<String, Object?>>>>);

  @override
  _i3.Future<_i2.Response<List<Map<String, Object?>>>> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i3.Future<_i2.Response<List<Map<String, Object?>>>>.value(
            _FakeResponse_0<List<Map<String, Object?>>>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.Response<List<Map<String, Object?>>>>.value(
                _FakeResponse_0<List<Map<String, Object?>>>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response<List<Map<String, Object?>>>>);
}
