name: api_store
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
