targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      go_router_builder:
        generate_for:
          include:
            - lib/**/app_routes.dart
      freezed:
        generate_for:
          include:
            - lib/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/**/*.dart
            - lib/**/provider.dart
        options:
          # 例外発生時にCheckedFromJsonExceptionをthrowする
          checked: true
          # ネストされたリストに対してtoJson/fromJsonをメソッド生成する
          explicit_to_json: true
          # field_rename: snake
