name: onetaplog
description: One tap to log it!
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analysis_logger:
    path: ../analysis_logger
  authenticator:
    path: ../authenticator
  awaitable_button: ^1.2.0
  cached_network_image: ^3.1.0
  convenient_widgets:
    path: ../convenient_widgets
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  go_router: ^4.4.1
  hooks_riverpod: ^2.0.0-dev.9
  intl: ^0.17.0
  json_annotation: ^4.6.0
  notification_receiver:
    path: ../notification_receiver
  pull_down_button: ^0.1.0-beta.8
  remote_parameter_fetcher:
    path: ../remote_parameter_fetcher
  shimmer: ^2.0.0
  themes:
    path: ../themes
  util:
    path: ../util

dev_dependencies:
  altive_lints: ^1.5.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  go_router_builder: ^1.0.10
  json_serializable: ^6.3.1

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  assets:
    style: dot-delimiter

flutter:
  # build_runnerが失敗するため
  # generate: true
  uses-material-design: true

  # assets:
