targets:
  $default:
    sources:
      include:
        - $package$ # Package metadata.
        - pubspec.yaml # FlutterGen configuration.
        - lib/** # Dart source files.
        - assets/** # Asset files for FlutterGen.
    builders:
      flutter_gen_runner:
        options:
          output: lib/gen/
