// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALNA5hH-DrVg1qUk2Ycqv-W2kGU1SpHaI',
    appId: '1:502626918852:web:8cc56d7467967ee5dfc491',
    messagingSenderId: '502626918852',
    projectId: 'flutter-app-template-stg',
    authDomain: 'flutter-app-template-stg.firebaseapp.com',
    storageBucket: 'flutter-app-template-stg.appspot.com',
    measurementId: 'G-9DC69MGFRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9WiqSDFa1HfI41cuhspZcyAlfWUz6174',
    appId: '1:727863764527:android:60de361331b312169688da',
    messagingSenderId: '727863764527',
    projectId: 'rolling-stock-app',
    databaseURL: 'https://rolling-stock-app.firebaseio.com',
    storageBucket: 'rolling-stock-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3580c_3e-U70CUKNt6WD8WG7I3OTZxE',
    appId: '1:727863764527:ios:286ee1a13b1d5a149688da',
    messagingSenderId: '727863764527',
    projectId: 'rolling-stock-app',
    databaseURL: 'https://rolling-stock-app.firebaseio.com',
    storageBucket: 'rolling-stock-app.appspot.com',
    androidClientId: '727863764527-gj1q890q471e4lb0tcuksnoofnl9t32t.apps.googleusercontent.com',
    iosClientId: '727863764527-6v90arqckamvcujn63gd9maevugk3mal.apps.googleusercontent.com',
    iosBundleId: 'jp.altive.rollingstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACYrCRpTpoH1dxPJY3atGxmwKmtXRdw24',
    appId: '1:502626918852:ios:99ee534eace74ff6dfc491',
    messagingSenderId: '502626918852',
    projectId: 'flutter-app-template-stg',
    storageBucket: 'flutter-app-template-stg.appspot.com',
    iosClientId:
        '502626918852-9h1ius8m1asenmeu9a770orn23jsmbh1.apps.googleusercontent.com',
    iosBundleId: 'jp.co.altive.fat.stg',
  );
}