// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpXjQcj2xdTqfCvlBLCLgmRYacrWjupU',
    appId: '1:1068511233454:web:575d437de3c7b4a3a6f43f',
    messagingSenderId: '1068511233454',
    projectId: 'flutter-app-template-dev',
    authDomain: 'flutter-app-template-dev.firebaseapp.com',
    storageBucket: 'flutter-app-template-dev.appspot.com',
    measurementId: 'G-8NN8E414GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi0VJj1BFgEqYeeSI1FHre_qBIIQ-MOW4',
    appId: '1:142133475394:android:10cd065710581da111d5db',
    messagingSenderId: '142133475394',
    projectId: 'restock-development',
    databaseURL: 'https://restock-development.firebaseio.com',
    storageBucket: 'restock-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYC4_k201RndoavDxMgCLg3dC0PRlTEeA',
    appId: '1:142133475394:ios:7a8bc0481f2fc53511d5db',
    messagingSenderId: '142133475394',
    projectId: 'restock-development',
    databaseURL: 'https://restock-development.firebaseio.com',
    storageBucket: 'restock-development.appspot.com',
    androidClientId: '142133475394-fkh3a282rjru9916h9mitits5rlmbuj9.apps.googleusercontent.com',
    iosClientId: '142133475394-qgfa8cnrtqo5ug6e7tqq0c2ln8lpbe3d.apps.googleusercontent.com',
    iosBundleId: 'jp.altive.rollingstock.development',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qF31ymtLr6G6T7vNtb0O3LVrZnZRVCY',
    appId: '1:1068511233454:ios:0fbb2ad807bb95dda6f43f',
    messagingSenderId: '1068511233454',
    projectId: 'flutter-app-template-dev',
    storageBucket: 'flutter-app-template-dev.appspot.com',
    iosClientId:
        '1068511233454-jqkcgldo7cro8bsap1j574959nmgfjqe.apps.googleusercontent.com',
    iosBundleId: 'jp.co.altive.fat.dev',
  );
}