// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0d24P1PrA5-PsldKLirtSROH-W1jLal4',
    appId: '1:1007652573613:web:95b16cd22289abbfbb1124',
    messagingSenderId: '1007652573613',
    projectId: 'altive-fat',
    authDomain: 'altive-fat.firebaseapp.com',
    storageBucket: 'altive-fat.appspot.com',
    measurementId: 'G-P8N1PB7S1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe8g8xklQh6VbTbNNUrozIGhEJInVYSnI',
    appId: '1:273222294304:android:490840a846ee465929d545',
    messagingSenderId: '273222294304',
    projectId: 're-stock',
    databaseURL: 'https://re-stock.firebaseio.com',
    storageBucket: 're-stock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7yY_1rpUB5xYo6DM19D9rg_Nu9WPiSDw',
    appId: '1:273222294304:ios:b94fef831522147c29d545',
    messagingSenderId: '273222294304',
    projectId: 're-stock',
    databaseURL: 'https://re-stock.firebaseio.com',
    storageBucket: 're-stock.appspot.com',
    androidClientId: '273222294304-3q91gcj6okqlu5amm02f8ognmqr4p3fa.apps.googleusercontent.com',
    iosClientId: '273222294304-vjukbcahpm2puf8so4eu7b3haghpojm2.apps.googleusercontent.com',
    iosBundleId: 'jp.altive.restock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_2h3SpFnoRfbIbfx7UYlktvWMQu5Edec',
    appId: '1:1007652573613:ios:bf46ce3fca7af889bb1124',
    messagingSenderId: '1007652573613',
    projectId: 'altive-fat',
    storageBucket: 'altive-fat.appspot.com',
    iosClientId:
        '1007652573613-2ggi30iortpdb6gilpfli5ouk6ruckhg.apps.googleusercontent.com',
    iosBundleId: 'jp.co.altive.fat',
  );
}