include: package:altive_lints/altive_lints.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/gen/*.dart"
    - "**/firebase_options_*.dart"
linter:
  rules:
    public_member_api_docs: false
