include: package:altive_lints/altive_lints.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/gen/*.dart"
    - "**/firebase_options_*.dart"
  errors:
    # for go_router 15.1.3 with go_router_builder 3.0.0.
    override_on_non_overriding_member: ignore
linter:
  rules:
    public_member_api_docs: false
    # Disabled to avoid conflict with format in Dart v3.7.0
    require_trailing_commas: false
