targets:
  $default:
    sources:
      include:
        - $package$ # Package metadata.
        - pubspec.yaml # FlutterGen and other builders configuration.
        - lib/** # Dart source files.
        - assets/** # Asset files for FlutterGen.
    builders:
      flutter_gen_runner:
        options:
          output: lib/gen/
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - duplicate_ignore
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      go_router_builder:
        generate_for:
          include:
            - lib/**/app_routes.dart
      json_serializable:
        generate_for:
          include:
            - lib/**/entities/*.dart
            - lib/**/model/*.dart
        options:
          # Throw CheckedFromJsonException when an exception occurs
          checked: true
          # Generate toJson/fromJson methods for nested lists
          explicit_to_json: true
          field_rename: snake
