targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      TypedGoRoute:
        generate_for:
          include:
            - lib/router/app_routes.dart
      freezed:
        generate_for:
          include:
            - lib/**/entities/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/**/entities/*.dart
        options:
          any_map: true
          # checked: true # 例外発生時にCheckedFromJsonExceptionをthrowする
          create_factory: true # xxxFromJson メソッドを生成
          create_to_json: true # toJson メソッドを生成
          disallow_unrecognized_keys: false # 認識できないキーがあった場合、UnrecognizedKeysExceptionをthrowする
          explicit_to_json: true # ネストされたリストに対してtoJson/fromJsonをメソッド生成
          field_rename: snake
