targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - duplicate_ignore
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      freezed:
        generate_for:
          include:
            - "**/entities/*.dart"
            - "**/models/*.dart"
      json_serializable:
        generate_for:
          include:
            - "**/entities/*.dart"
            - "**/models/*.dart"
        options:
          # 例外発生時にCheckedFromJsonExceptionをthrowする
          checked: true
          # ネストされたリストに対してtoJson/fromJsonをメソッド生成する
          explicit_to_json: true
      riverpod_generator:
        generate_for:
          include:
            - "**/providers/*.dart"
            - "**/*provider.dart"
