name: Upload Flutter iOS App
description: "Upload Flutter iOS App"
inputs:
  working_directory:
    description: "working-directory. example: packages/flutter_app"
    required: false
    default: "./"
  flavor:
    description: "Flavor name"
    required: true
  bundle_name:
    description: "CFBundleName"
    required: true
  profile_name:
    description: "Provisioning Profile file name"
    required: true
  build_number:
    description: "Build number"
    required: true
  provisioning_profile:
    description: ""
    required: true
  certificate_p12:
    description: ""
    required: true
  certificate_password:
    description: ""
    required: true
  apple_id:
    description: ""
    required: true
  app_specific_password:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: Import Provisioning Profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo -n ${{ inputs.provisioning_profile }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/${{ inputs.profile_name }}.mobileprovision
      shell: bash

    - name: Import Code-Signing Certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        keychain: signing_temp
        create-keychain: true
        p12-file-base64: ${{ inputs.certificate_p12 }}
        p12-password: ${{ inputs.certificate_password }}

    - name: Create ipa file
      run: flutter build ipa --dart-define=FLAVOR=${{ inputs.flavor }} --export-options-plist=ios/${{ inputs.flavor }}/ExportOptions.plist --build-number ${{ inputs.build_number }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Upload to AppStoreConnect
      run: xcrun altool --upload-app --file "./build/ios/ipa/${{ inputs.bundle_name }}.ipa" --type ios --username ${{ inputs.apple_id }} --password ${{ inputs.app_specific_password}}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
