name: Send notification to Slack
description: "Send notification to Slack"
inputs:
  text:
    description: "Message text"
    required: true
  incoming_webhook_url:
    description: "Slack incoming webhook URL"
    required: true
runs:
  using: "composite"
  steps:
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "attachments": [
              {
                "color": "${{ (job.status == 'success' && 'good') || 'danger' }}",
                "author_name": "${{ github.event.sender.login }}",
                "author_link": "https://github.com/${{ github.event.sender.login }}",
                "author_icon": "$ {{ github.event.sender.avatar_url }}",
                "title": "${{ job.status }}",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "${{ inputs.text }}",
                "footer": "Send from GitHub Actions"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ inputs.incoming_webhook_url }}
