name: Flutter Analyze

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Parse Flutter version
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install Melos
        uses: bluefireteam/melos-action@v1

      - name: Which
        run: which flutter

      - name: Create dummy env files
        run: |
          touch packages/graphql_playground/.env
          touch packages/restock_app/.env

      - name: Analyze project
        run: melos run analyze

      - name: Check for the existence of unformatted files
        run: melos run format
