name: Flutter Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Parse Flutter version
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Install Melos
        uses: bluefireteam/melos-action@v1

      - name: Create dummy env files
        run: |
          touch packages/flutter_app/env/.env.dev
          touch packages/flutter_app/env/.env.stg
          touch packages/flutter_app/env/.env.prod
          touch packages/graphql_playground/.env
          touch packages/restock_app/.env

      - name: Run unit tests
        run: melos run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ~/coverage/lcov.info
          fail_ci_if_error: false

      - name: Send notification to Slack
        if: always()
        uses: ./.github/actions/send_notification_to_slack
        with:
          text: "Finished testing on: ${{ github.event.pull_request.html_url }}"
          incoming_webhook_url: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
