name: Flutter pub upgrade

on:
  workflow_dispatch: # 手動実行可能化
  schedule: # https://docs.github.com/ja/actions/reference/events-that-trigger-workflows#scheduled
  - cron: '0 8 1 * *' # '分 時 日 月 曜日' (UTC)

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Parse Flutter version
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Install Melos
        uses: bluefireteam/melos-action@v1
          
      - name: Upgrade Dependencies
        run: melos run upgrade
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: scheduled/update-packages
          delete-branch: true
          commit-message: 'build: upgrade Flutter pub packages'
          title: '[Bot] Upgrade Flutter pub packages'
          body: |
            ## Overview
            パッケージ更新のPull Requestです。
            定期スケジュールに基づいて作成されています。
            
            レビュアーは動作確認を行い、必要であればコードを修正した上でマージしてください。
            
            ---
            
            [create-pull-request](https://github.com/peter-evans/create-pull-request)により作成されました。
          labels: scheduled
