name: Upload Flutter iOS App

on:
  workflow_call:
    inputs:
      flavor:
        description: "Flavor name"
        required: true
        type: string
      bundle_name:
        description: "CFBundleName"
        required: true
        type: string
      profile_name:
        description: "Provisioning Profile file name"
        required: true
        type: string
      build_number:
        description: "Build number"
        required: true
        type: string
    secrets:
      provisioning_profile:
        required: true
      certificate_p12:
        required: true
      certificate_password:
        required: true
      apple_id:
        required: true
      app_specific_password:
        required: true
      slack_incoming_webhook_url:
        required: true
jobs:
  upload_ios_app:
    name: Upload iOS App
    runs-on: macos-latest

    steps:
      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.provisioning_profile }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/${{ inputs.profile_name }}.mobileprovision

      - name: Import Code-Signing Certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          keychain: signing_temp
          create-keychain: true
          p12-file-base64: ${{ secrets.certificate_p12 }}
          p12-password: ${{ secrets.certificate_password }}

      - name: Create ipa file
        run: flutter build ipa --dart-define=FLAVOR=${{ inputs.flavor }} --export-options-plist=ios/${{ inputs.flavor }}/ExportOptions.plist --build-number ${{ inputs.build_number }}

      - name: Upload to AppStoreConnect
        run: xcrun altool --upload-app --file "./build/ios/ipa/${{ inputs.bundle_name }}.ipa" --type ios --username ${{ secrets.apple_id }} --password ${{ secrets.app_specific_password}}
