name: Upload FAT iOS App (Staging)

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "packages/flutter_app/**"

defaults:
  run:
    working-directory: packages/flutter_app

env:
  working_directory: packages/flutter_app
  flavor: stg

jobs:
  upload_app:
    name: Upload App
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Flutter from repository
        uses: ./.github/actions/setup_flutter
        with:
          ref: stable
          working_directory: ${{ env.working_directory }}

      - name: Upload Flutter iOS App
        uses: ./.github/actions/upload_ios_app
        with:
          working_directory: ${{ env.working_directory }}
          flavor: ${{ env.flavor }}
          bundle_name: FAT.stg
          profile_name: AppStore_jpcoaltivefatstg
          build_number: ${{ github.run_number}}
          provisioning_profile: ${{ secrets.PROVISIONING_PROFILE }}
          certificate_p12: ${{ secrets.CERTIFICATES_P12 }}
          certificate_password: ${{ secrets.CERTIFICATE_PASSWORD }}
          apple_id: ${{ secrets.APPLE_ID }}
          app_specific_password: ${{ secrets.APPLE_APP_PASSWORD }}

      - name: Send notification to Slack
        if: always()
        uses: ./.github/actions/send_notification_to_slack
        with:
          text: "iOS app upload in ${{ env.flavor }}"
          incoming_webhook_url: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
