name: Upload Flutter iOS App

on:
  workflow_call:
    inputs:
      package:
        description: "Package directory name"
        required: true
        type: string
      flavor:
        description: "Flavor name"
        required: true
        type: string
      bundle_name:
        description: "CFBundleName"
        required: true
        type: string
      profile_name:
        description: "Provisioning Profile finle name"
        required: true
        type: string
      build_number:
        description: "Build number"
        required: true
        type: string
    secrets:
      certificate_p12:
        required: true
      certificate_password:
        required: true
      apple_id:
        required: true
      app_specific_password:
        required: true
      slack_incoming_webhook_url:
        required: true

defaults:
  run:
    working-directory: packages/${{ inputs.package }}

jobs:
  upload_ios_app:
    name: Upload iOS App
    runs-on: macos-latest

    steps:
      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/${{ inputs.profile_name }}.mobileprovision

      - name: Import Code-Signing Certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          keychain: signing_temp
          create-keychain: true
          p12-file-base64: ${{ secrets.certificate_p12 }}
          p12-password: ${{ secrets.certificate_password }}

      - name: Create ipa file
        run: flutter build ipa --dart-define=FLAVOR=${{ flavor }} --export-options-plist=ios/${{ flavor }}/ExportOptions.plist --build-number ${{ build_number }}

      - name: Upload to AppStoreConnect
        run: xcrun altool --upload-app --file "./build/ios/ipa/${{ bundle_name }}.ipa" --type ios --username ${{ apple_id }} --password ${{ app_specific_password}}
