include: package:altive_lints/altive_lints.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
linter:
  rules:
    # 数が多いため一時的に無効
    use_build_context_synchronously: false
    use_key_in_widget_constructors: false
    