targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      freezed:
        generate_for:
          include:
            - lib/**/*state.dart
            - lib/**/models/amazon/*.dart
            - lib/**/models/firestore/**/*.dart
            - lib/**/*_model.dart
            - lib/**/*_entity.dart
            - lib/**/*_payload.dart
            - lib/**/*_parameter.dart
            - lib/**/result.dart
      json_serializable:
        generate_for:
          include:
            - lib/**/*state.dart
            - lib/**/models/amazon/*.dart
            - lib/**/models/firestore/**/*.dart
            - lib/**/*_model.dart
            - lib/**/*_entity.dart
            - lib/**/*_payload.dart
            - lib/**/*_parameter.dart
        options:
          # 例外発生時にCheckedFromJsonExceptionをthrowする
          checked: true
          # ネストされたリストに対してtoJson/fromJsonをメソッド生成する
          explicit_to_json: true
