name: restock
description: ReStock
publish_to: "none"
version: 2.10.0+90

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.0.1
  amazon_paapi:
    path: ../amazon_paapi/
  analysis_logger:
    path: ../analysis_logger/
  app_review: ^2.1.1+1
  app_settings: ^4.1.8
  async: ^2.6.1
  authenticator:
    path: ../authenticator
  cloud_firestore: ^3.4.6
  collection: ^1.15.0
  convenient_widgets:
    path: ../convenient_widgets/
  crypto: ^3.0.1
  cupertino_icons: ^1.0.5
  device_info: ^2.0.2
  enum_to_string: ^2.0.1
  extended_image: ^6.0.1
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_dynamic_links: ^4.3.6
  firebase_messaging: ^12.0.3
  firebase_performance: ^0.8.2+3
  firebase_remote_config: ^2.0.16
  firebase_storage: ^10.3.7
  firestore_ref: ^0.13.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  google_sign_in: ^5.4.1
  hooks_riverpod: ^2.0.0-dev.5
  http: ^0.13.3
  image_cropper: ^2.0.0
  image_picker: ^0.8.1+2
  intl: ^0.17.0
  json_annotation: ^4.6.0
  material_design_icons_flutter: ^5.0.6595
  nested: ^1.0.0
  notification_receiver:
    path: ../notification_receiver/
  notification_sender:
    path: ../notification_sender/
  package_info: ^2.0.2
  purchases_flutter: ^4.2.1
  quiver: ^3.0.1
  recase: ^4.0.0
  share_plus: ^4.0.10
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^4.0.0
  simple_logger: ^1.8.1
  themes:
    path: ../themes/
  timezone: ^0.9.0
  tuple: ^2.0.0
  url_launcher: ^6.1.4
  uuid: ^3.0.4
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.5.0
  build_runner: ^2.2.1
  flutter_gen_runner: ^4.3.0
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mockito: ^5.2.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  assets:
    style: dot-delimiter

flutter:
  uses-material-design: true

  assets:
    - env/
    - assets/app_icons/
    - assets/images/
    - assets/images/reception_featured_dark.png
    - assets/images/reception_featured_light.png

  fonts:
    - family: M_PLUS_Rounded_1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
