name: restock
description: ReStock
publish_to: 'none'
version: 2.9.2+89

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  adaptive_dialog: ^1.0.1
  amazon_paapi:
    path: ../amazon_paapi/
  analysis_logger:
    path: ../analysis_logger/
  app_review: ^2.1.1+1
  async: ^2.6.1
  cloud_firestore: ^3.1.10
  collection: ^1.15.0
  convenient_widgets:
    path: ../convenient_widgets/
  crypto: ^3.0.1
  cupertino_icons: ^1.0.5
  device_info: ^2.0.2
  enum_to_string: ^2.0.1
  extended_image: ^6.0.1
  firebase_auth: ^3.1.5
  firebase_core: ^1.14.0
  firebase_dynamic_links: ^4.3.3
  firebase_messaging: ^12.0.0
  firebase_performance: ^0.8.0+7
  firebase_remote_config: ^2.0.9
  firebase_storage: ^10.0.7
  firestore_ref: ^0.13.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_local_notifications: ^9.6.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.1
  google_sign_in: ^5.3.3
  hooks_riverpod: ^2.0.0-dev.5
  http: ^0.13.3
  image_cropper: ^2.0.0
  image_picker: ^0.8.1+2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  material_design_icons_flutter: ^5.0.6595
  nested: ^1.0.0
  notification_receiver:
    path: ../notification_receiver/
  package_info: ^2.0.2
  permission_handler: ^9.2.0
  purchases_flutter: ^3.3.0
  quiver: ^3.0.1
  recase: ^4.0.0
  share_plus: ^4.0.10
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^4.0.0
  simple_logger: ^1.8.1
  themes:
    path: ../themes/
  timezone: ^0.8.0
  tuple: ^2.0.0
  url_launcher: ^6.1.4
  uuid: ^3.0.4
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.2.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.3.1
  mockito: ^5.2.0

dependency_overrides:

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/app_icons/
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    - assets/images/apple_logo_black.png
    - assets/images/apple_logo_white.png
    - assets/images/apple_logo_white.png
    - assets/images/btn_google_light_normal.png
    - assets/images/reception_featured_dark.png
    - assets/images/reception_featured_light.png

  fonts:
    - family: M_PLUS_Rounded_1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
